### ISSUE TITLE
Requirements.txt missing itsdangerous

### ISSUE THREAD

**Issue by wraythezw** [brianwarehime/threatnote#27]
Starting threatnote_threatnote_1 ... done
Attaching to threatnote_threatnote_1
threatnote_1  | [2022-05-18 06:44:08 +0000] [8] [INFO] Starting gunicorn 20.1.0
threatnote_1  | [2022-05-18 06:44:08 +0000] [8] [INFO] Listening at: http://0.0.0.0:5000 (8)
threatnote_1  | [2022-05-18 06:44:08 +0000] [8] [INFO] Using worker: sync
threatnote_1  | [2022-05-18 06:44:08 +0000] [16] [INFO] Booting worker with pid: 16
threatnote_1  | [2022-05-18 06:44:09 +0000] [17] [INFO] Booting worker with pid: 17
threatnote_1  | [2022-05-18 06:44:09 +0000] [18] [INFO] Booting worker with pid: 18
threatnote_1  | [2022-05-18 06:44:09 +0000] [19] [INFO] Booting worker with pid: 19
threatnote_1  | [2022-05-18 06:44:11 +0000] [17] [ERROR] Exception in worker process
threatnote_1  | Traceback (most recent call last):
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
threatnote_1  |     worker.init_process()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
threatnote_1  |     self.load_wsgi()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
threatnote_1  |     self.wsgi = self.app.wsgi()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
threatnote_1  |     self.callable = self.load()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
threatnote_1  |     return self.load_wsgiapp()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
threatnote_1  |     return util.import_app(self.app_uri)
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
threatnote_1  |     mod = importlib.import_module(module)
threatnote_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
threatnote_1  |     return _bootstrap._gcd_import(name[level:], package, level)
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
threatnote_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
threatnote_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
threatnote_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
threatnote_1  |   File "/app/main.py", line 33, in <module>
threatnote_1  |     import api
threatnote_1  |   File "/app/api.py", line 8, in <module>
threatnote_1  |     from itsdangerous import (TimedJSONWebSignatureSerializer
threatnote_1  | ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)
threatnote_1  | [2022-05-18 06:44:11 +0000] [17] [INFO] Worker exiting (pid: 17)
threatnote_1  | [2022-05-18 06:44:11 +0000] [18] [ERROR] Exception in worker process
threatnote_1  | Traceback (most recent call last):
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
threatnote_1  |     worker.init_process()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
threatnote_1  |     self.load_wsgi()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
threatnote_1  |     self.wsgi = self.app.wsgi()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
threatnote_1  |     self.callable = self.load()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
threatnote_1  |     return self.load_wsgiapp()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
threatnote_1  |     return util.import_app(self.app_uri)
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
threatnote_1  |     mod = importlib.import_module(module)
threatnote_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
threatnote_1  |     return _bootstrap._gcd_import(name[level:], package, level)
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
threatnote_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
threatnote_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
threatnote_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
threatnote_1  |   File "/app/main.py", line 33, in <module>
threatnote_1  |     import api
threatnote_1  |   File "/app/api.py", line 8, in <module>
threatnote_1  |     from itsdangerous import (TimedJSONWebSignatureSerializer
threatnote_1  | ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)
threatnote_1  | [2022-05-18 06:44:11 +0000] [18] [INFO] Worker exiting (pid: 18)
threatnote_1  | [2022-05-18 06:44:11 +0000] [16] [ERROR] Exception in worker process
threatnote_1  | Traceback (most recent call last):
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
threatnote_1  |     worker.init_process()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
threatnote_1  |     self.load_wsgi()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
threatnote_1  |     self.wsgi = self.app.wsgi()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
threatnote_1  |     self.callable = self.load()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
threatnote_1  |     return self.load_wsgiapp()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
threatnote_1  |     return util.import_app(self.app_uri)
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
threatnote_1  |     mod = importlib.import_module(module)
threatnote_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
threatnote_1  |     return _bootstrap._gcd_import(name[level:], package, level)
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
threatnote_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
threatnote_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
threatnote_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
threatnote_1  |   File "/app/main.py", line 33, in <module>
threatnote_1  |     import api
threatnote_1  |   File "/app/api.py", line 8, in <module>
threatnote_1  |     from itsdangerous import (TimedJSONWebSignatureSerializer
threatnote_1  | ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)
threatnote_1  | [2022-05-18 06:44:11 +0000] [16] [INFO] Worker exiting (pid: 16)
threatnote_1  | [2022-05-18 06:44:11 +0000] [19] [ERROR] Exception in worker process
threatnote_1  | Traceback (most recent call last):
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
threatnote_1  |     worker.init_process()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
threatnote_1  |     self.load_wsgi()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
threatnote_1  |     self.wsgi = self.app.wsgi()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
threatnote_1  |     self.callable = self.load()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
threatnote_1  |     return self.load_wsgiapp()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
threatnote_1  |     return util.import_app(self.app_uri)
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
threatnote_1  |     mod = importlib.import_module(module)
threatnote_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
threatnote_1  |     return _bootstrap._gcd_import(name[level:], package, level)
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
threatnote_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
threatnote_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
threatnote_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
threatnote_1  |   File "/app/main.py", line 33, in <module>
threatnote_1  |     import api
threatnote_1  |   File "/app/api.py", line 8, in <module>
threatnote_1  |     from itsdangerous import (TimedJSONWebSignatureSerializer
threatnote_1  | ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)
threatnote_1  | [2022-05-18 06:44:11 +0000] [19] [INFO] Worker exiting (pid: 19)
threatnote_1  | [2022-05-18 06:44:11 +0000] [8] [WARNING] Worker with pid 18 was terminated due to signal 15
threatnote_1  | [2022-05-18 06:44:11 +0000] [8] [WARNING] Worker with pid 19 was terminated due to signal 15
threatnote_1  | [2022-05-18 06:44:11 +0000] [8] [WARNING] Worker with pid 16 was terminated due to signal 15
threatnote_1  | [2022-05-18 06:44:11 +0000] [8] [INFO] Shutting down: Master
threatnote_1  | [2022-05-18 06:44:11 +0000] [8] [INFO] Reason: Worker failed to boot.

**Comment by wraythezw** [comment]
Added itsdangerous==2.0.1
to the end of requirements.txt and rebuilt the image, after which starts normally.
