### ISSUE TITLE
Can't deploy docker with docker-compose

### ISSUE THREAD

**Issue by cyberdometanza** [brianwarehime/threatnote#29]
Hi all,
at the moment I launch docker-compose up command, it starts with gunicorn launching different workers but they fail returning me these errors:

_Starting threatnote_threatnote_1 ... done
Attaching to threatnote_threatnote_1
threatnote_1  | [2022-09-07 18:12:21 +0000] [7] [INFO] Starting gunicorn 20.1.0
threatnote_1  | [2022-09-07 18:12:21 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
threatnote_1  | [2022-09-07 18:12:21 +0000] [7] [INFO] Using worker: sync
threatnote_1  | [2022-09-07 18:12:21 +0000] [15] [INFO] Booting worker with pid: 15
threatnote_1  | [2022-09-07 18:12:21 +0000] [16] [INFO] Booting worker with pid: 16
threatnote_1  | [2022-09-07 18:12:21 +0000] [17] [INFO] Booting worker with pid: 17
threatnote_1  | [2022-09-07 18:12:21 +0000] [18] [INFO] Booting worker with pid: 18
threatnote_1  | [2022-09-07 18:12:25 +0000] [18] [ERROR] Exception in worker process
threatnote_1  | Traceback (most recent call last):
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
threatnote_1  |     worker.init_process()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
threatnote_1  |     self.load_wsgi()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
threatnote_1  |     self.wsgi = self.app.wsgi()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
threatnote_1  |     self.callable = self.load()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
threatnote_1  |     return self.load_wsgiapp()
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
threatnote_1  |     return util.import_app(self.app_uri)
threatnote_1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
threatnote_1  |     mod = importlib.import_module(module)
threatnote_1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
threatnote_1  |     return _bootstrap._gcd_import(name[level:], package, level)
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
threatnote_1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
threatnote_1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
threatnote_1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
threatnote_1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
threatnote_1  |   File "/app/main.py", line 33, in <module>
threatnote_1  |     import api
threatnote_1  |   File "/app/api.py", line 8, in <module>
threatnote_1  |     from itsdangerous import (TimedJSONWebSignatureSerializer
threatnote_1  | ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)_

Apparently main.py have some problem to import a specific module from "itsdangerous". I checked and the class is correctly declared.
I already tried to solve some dependencies with the requirements but the error is still there.

Thank you.

**Comment by cyberdometanza** [comment]
Any news about this?
Thanks!

**Comment by mxamusic** [comment]
I am facing the same issue here any update. did you manage to get it to work

**Comment by strideod** [comment]
This issue accounts for the itsdangerous module, [https://github.com/brianwarehime/threatnote/issues/27#issuecomment-1129647517] from reading the module docs, `TimedJSONWebSignatureSerializer` is deprecated. I am now running into a flask issue which may need a new issue.

**Comment by cryxnet** [comment]
Its still not fixed

**Comment by khalavak** [comment]
Hello....this is still not fixed. Any updates ongoing for this?

**Comment by Meeengoh** [comment]
> Hello....this is still not fixed. Any updates ongoing for this?

add itsdangerous==2.0.1 (`echo "itsdangerous==2.0.1" >> requirements.txt`) to your requirements.txt file and rebuild (`docker build . --tag theatnote`)  before running `docker-compose up`. I had port 5000 already in use and had to change the port being used in a couple of files before being able to access the web front.

Hope this helps.
